#!bash
apt update
apt upgrade
apt install apt bash busybox command-not-found coreutils dash dpkg findutils gawk git gpgv grep gzip htop hub less libandroid-support liblzma man mc ncurses openssh postgresql python readline rsync screen screenfetch tar termux-tools tree unrar unzip vim-python wget zip tmux

if ! [ -e ~/.vim/bundle/Vundle.vim ] 
then
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim -c 'PluginInstall' -c 'qa'

